# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/coredns/caddy
%global goipath         github.com/coredns/caddy
Version:                1.1.1

%gometa

%global common_description %{expand:
Fast, multi-platform web server with automatic HTTPS.}

%global golicenses      LICENSE.txt
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Fast, multi-platform web server with automatic HTTPS

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/flynn/go-shlex)
BuildRequires:  golang(github.com/google/uuid)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Sep 05 2021 Petr Menšík <pemensik@redhat.com> - 1.1.1-1%{?dist}
- Initial package

